// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ClusterInfoPacket } from '../../jdmb/node/cluster-info-packet.js';
import { HelloPacket } from '../../jdmb/node/hello-packet.js';


export enum AnyPacket {
  NONE = 0,
  HelloPacket = 1,
  ClusterInfoPacket = 2
}

export function unionToAnyPacket(
  type: AnyPacket,
  accessor: (obj:ClusterInfoPacket|HelloPacket) => ClusterInfoPacket|HelloPacket|null
): ClusterInfoPacket|HelloPacket|null {
  switch(AnyPacket[type]) {
    case 'NONE': return null; 
    case 'HelloPacket': return accessor(new HelloPacket())! as HelloPacket;
    case 'ClusterInfoPacket': return accessor(new ClusterInfoPacket())! as ClusterInfoPacket;
    default: return null;
  }
}

export function unionListToAnyPacket(
  type: AnyPacket, 
  accessor: (index: number, obj:ClusterInfoPacket|HelloPacket) => ClusterInfoPacket|HelloPacket|null, 
  index: number
): ClusterInfoPacket|HelloPacket|null {
  switch(AnyPacket[type]) {
    case 'NONE': return null; 
    case 'HelloPacket': return accessor(index, new HelloPacket())! as HelloPacket;
    case 'ClusterInfoPacket': return accessor(index, new ClusterInfoPacket())! as ClusterInfoPacket;
    default: return null;
  }
}
