// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class NodeInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NodeInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

id(index: number):number|null {
    return this.bb!.readUint8(this.bb_pos + 0 + index);
}

ip():number {
  return this.bb!.readUint32(this.bb_pos + 32);
}

port():number {
  return this.bb!.readUint16(this.bb_pos + 36);
}

static sizeOf():number {
  return 40;
}

static createNodeInfo(builder:flatbuffers.Builder, id: number[]|null, ip: number, port: number):flatbuffers.Offset {
  builder.prep(4, 40);
  builder.pad(2);
  builder.writeInt16(port);
  builder.writeInt32(ip);

  for (let i = 31; i >= 0; --i) {
    builder.writeInt8((id?.[i] ?? 0));

  }

  return builder.offset();
}

}
